import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../data/local/isar_db.dart';

final l10nProvider = Provider<L10n>((ref) {
  final langCode = ref.watch(languageProvider).value ?? 'id-ID';
  return L10n(langCode);
});

final languageProvider = FutureProvider<String>((ref) async {
  final isar = ref.read(isarDbProvider);
  final settings = await isar.getSettings();
  return settings.languageCode;
});

class L10n {
  final String langCode;
  L10n(this.langCode);

  static const List<String> supportedLanguages = [
    'id-ID', 'en-US', 'ar-SA', 'de-DE', 'nl-NL', 'zh-CN', 'ja-JP', 'ko-KR', 'hi-IN', 'es-ES', 'ru-RU', 'fr-FR', 'tr-TR'
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'id-ID': {
      'app_name': 'PELITA',
      'welcome': 'Selamat datang di Pelita.',
      'nav_hint': 'Geser kanan kiri untuk navigasi menu.',
      'text_scanner': 'Pemindai Teks',
      'currency_detector': 'Deteksi Uang',
      'medication_assistant': 'Asisten Obat',
      'voice_memo': 'Catatan Suara',
      'spatial_nav': 'Navigasi Spasial',
      'islamic_features': 'Fitur Islam',
      'entertainment': 'Hiburan dan Game',
      'status_center': 'Pusat Status',
      'settings': 'Pengaturan',
      'back': 'Kembali',
      'tap_to_enter': 'Ketuk dua kali untuk masuk.',
      'entering': 'Masuk ke',
      'help_hint': 'Bantuan. Geser kanan kiri untuk navigasi.',
      'speed': 'Kecepatan Suara',
      'pitch': 'Nada Suara',
      'change_language': 'Ganti Bahasa',
      'contrast_theme': 'Tema Kontras',
      'fall_detection': 'Status Deteksi Jatuh',
      'settings_welcome': 'Pengaturan. Geser kanan kiri untuk kategori, atas bawah untuk mengatur.',
      'swipe_v_to_adjust': 'Geser atas bawah untuk mengatur.',
      'lang_name': 'Indonesia',
      'lang_changed_to': 'Bahasa diubah ke',
    },
    'en-US': {
      'app_name': 'PELITA',
      'welcome': 'Welcome to Pelita.',
      'nav_hint': 'Swipe left or right to navigate.',
      'text_scanner': 'Text Scanner',
      'currency_detector': 'Currency Detector',
      'medication_assistant': 'Medication Assistant',
      'voice_memo': 'Voice Memo',
      'spatial_nav': 'Spatial Navigation',
      'islamic_features': 'Islamic Features',
      'entertainment': 'Entertainment and Games',
      'status_center': 'Status Center',
      'settings': 'Settings',
      'back': 'Back',
      'tap_to_enter': 'Double tap to enter.',
      'entering': 'Entering',
      'help_hint': 'Help. Swipe left or right to navigate.',
      'speed': 'Speech Speed',
      'pitch': 'Speech Pitch',
      'change_language': 'Change Language',
      'contrast_theme': 'High Contrast Theme',
      'fall_detection': 'Fall Detection Status',
      'settings_welcome': 'Settings. Swipe left or right for categories, up or down to adjust.',
      'swipe_v_to_adjust': 'Swipe up or down to adjust.',
      'lang_name': 'English',
      'lang_changed_to': 'Language changed to',
    },
    'ar-SA': {
      'app_name': 'بليتا',
      'welcome': 'مرحباً بك في بليتا.',
      'nav_hint': 'اسحب للتنقل.',
      'text_scanner': 'قارئ النصوص',
      'currency_detector': 'كاشف العملات',
      'medication_assistant': 'مساعد الدواء',
      'voice_memo': 'مذكرة صوتية',
      'spatial_nav': 'الملاحة الفضائية',
      'islamic_features': 'الميزات الإسلامية',
      'entertainment': 'الترفيه والألعاب',
      'status_center': 'مركز الحالة',
      'settings': 'الإعدادات',
      'back': 'رجوع',
      'tap_to_enter': 'انقر مرتين للدخول.',
      'entering': 'الدخول إلى',
      'help_hint': 'مساعدة. اسحب للتنقل.',
      'speed': 'سرعة الصوت',
      'pitch': 'نغمة الصوت',
      'change_language': 'تغيير اللغة',
      'contrast_theme': 'سمة التباين العالي',
      'fall_detection': 'حالة كشف السقوط',
      'settings_welcome': 'الإعدادات. اسحب للفئات، واللأعلى للضبط.',
      'swipe_v_to_adjust': 'اسحب للأعلى للضبط.',
      'lang_name': 'العربية',
      'lang_changed_to': 'تم تغيير اللغة إلى',
    },
    'de-DE': {
      'app_name': 'PELITA',
      'welcome': 'Willkommen bei Pelita.',
      'nav_hint': 'Wischen Sie nach links oder rechts.',
      'text_scanner': 'Text-Scanner',
      'currency_detector': 'Währungserkennung',
      'medication_assistant': 'Medikamenten-Assistent',
      'voice_memo': 'Sprachmemo',
      'spatial_nav': 'Räumliche Navigation',
      'islamic_features': 'Islamische Funktionen',
      'entertainment': 'Unterhaltung und Spiele',
      'status_center': 'Status-Center',
      'settings': 'Einstellungen',
      'back': 'Zurück',
      'tap_to_enter': 'Doppeltippen zum Aufrufen.',
      'entering': 'Eintreten in',
      'help_hint': 'Hilfe. Horizontal wischen.',
      'speed': 'Sprechgeschwindigkeit',
      'pitch': 'Tonhöhe',
      'change_language': 'Sprache ändern',
      'contrast_theme': 'Kontrastreiches Thema',
      'fall_detection': 'Sturzerkennung',
      'settings_welcome': 'Einstellungen. Wischen zum Anpassen.',
      'swipe_v_to_adjust': 'Vertikal wischen zum Anpassen.',
      'lang_name': 'Deutsch',
      'lang_changed_to': 'Sprache geändert auf',
    },
    'nl-NL': {
      'app_name': 'PELITA',
      'welcome': 'Welkom bij Pelita.',
      'nav_hint': 'Veeg naar links of rechts.',
      'text_scanner': 'Tekstscanner',
      'currency_detector': 'Valutadetector',
      'medication_assistant': 'Medicatie-assistent',
      'voice_memo': 'Spraakmemo',
      'spatial_nav': 'Ruimtelijke navigatie',
      'islamic_features': 'Islamitische functies',
      'entertainment': 'Entertainment en spellen',
      'status_center': 'Statuscentrum',
      'settings': 'Instellingen',
      'back': 'Terug',
      'tap_to_enter': 'Dubbeltik om te openen.',
      'entering': 'Binnengaan',
      'help_hint': 'Hulp. Veeg horizontaal.',
      'speed': 'Spraaksnelheid',
      'pitch': 'Toonhoogte',
      'change_language': 'Taal wijzigen',
      'contrast_theme': 'Hoog contrast thema',
      'fall_detection': 'Valdetectie status',
      'settings_welcome': 'Instellingen. Veeg om aan te passen.',
      'swipe_v_to_adjust': 'Veeg verticaal om aan te passen.',
      'lang_name': 'Nederlands',
      'lang_changed_to': 'Taal gewijzigd naar',
    },
    'zh-CN': {
      'app_name': 'PELITA',
      'welcome': '欢迎使用 Pelita。',
      'nav_hint': '左右滑动进行导航。',
      'text_scanner': '文本扫描仪',
      'currency_detector': '货币检测器',
      'medication_assistant': '用药助手',
      'voice_memo': '语音备忘录',
      'spatial_nav': '空间导航',
      'islamic_features': '伊斯兰功能',
      'entertainment': '娱乐和游戏',
      'status_center': '状态中心',
      'settings': '设置',
      'back': '返回',
      'tap_to_enter': '双击进入。',
      'entering': '正在进入',
      'help_hint': '帮助。左右滑动。',
      'speed': '语速',
      'pitch': '语调',
      'change_language': '更改语言',
      'contrast_theme': '高对比度主题',
      'fall_detection': '跌倒检测状态',
      'settings_welcome': '设置。上下滑动调节。',
      'swipe_v_to_adjust': '上下滑动调节。',
      'lang_name': '中文',
      'lang_changed_to': '语言已更改为',
    },
    'ja-JP': {
      'app_name': 'PELITA',
      'welcome': 'Pelitaへようこそ。',
      'nav_hint': '左右にスワイプして移動します。',
      'text_scanner': 'テキストスキャナー',
      'currency_detector': '通貨検出器',
      'medication_assistant': '服薬アシスタント',
      'voice_memo': 'ボイスメモ',
      'spatial_nav': '空間ナビゲーション',
      'islamic_features': 'イスラム機能',
      'entertainment': 'エンターテインメントとゲーム',
      'status_center': 'ステータスセンター',
      'settings': '設定',
      'back': '戻る',
      'tap_to_enter': 'ダブルタップで入力します。',
      'entering': '入室中',
      'help_hint': 'ヘルプ。左右にスワイプ。',
      'speed': '読み上げ速度',
      'pitch': '読み上げの高さ',
      'change_language': '言語を変更',
      'contrast_theme': 'ハイコントラストテーマ',
      'fall_detection': '転倒検知ステータス',
      'settings_welcome': '設定。上下にスワイプして調整。',
      'swipe_v_to_adjust': '上下スワイプして調整。',
      'lang_name': '日本語',
      'lang_changed_to': '言語が次のように変更されました',
    },
    'ko-KR': {
      'app_name': 'PELITA',
      'welcome': 'Pelita에 오신 것을 환영합니다.',
      'nav_hint': '좌우로 스와이프하여 탐색하세요.',
      'text_scanner': '텍스트 스캐너',
      'currency_detector': '화폐 감지기',
      'medication_assistant': '약 복용 보조',
      'voice_memo': '음성 메모',
      'spatial_nav': '공간 내비게이션',
      'islamic_features': '이슬람 기능',
      'entertainment': '엔터테인먼트 및 게임',
      'status_center': '상태 센터',
      'settings': '설정',
      'back': '뒤로',
      'tap_to_enter': '두 번 탭하여 입장하세요.',
      'entering': '입장 중',
      'help_hint': '도움말. 좌우로 스와이프.',
      'speed': '음성 속도',
      'pitch': '음성 높낮이',
      'change_language': '언어 변경',
      'contrast_theme': '고대비 테마',
      'fall_detection': '낙상 감지 상태',
      'settings_welcome': '설정. 상하로 스와이프하여 조정.',
      'swipe_v_to_adjust': '상하로 스와이프하여 조정.',
      'lang_name': '한국어',
      'lang_changed_to': '언어가 다음으로 변경되었습니다',
    },
    'hi-IN': {
      'app_name': 'PELITA',
      'welcome': 'Pelita में आपका स्वागत है।',
      'nav_hint': 'नेविगेट करने के लिए बाएं या दाएं स्वाइप करें।',
      'text_scanner': 'टेक्स्ट स्कैनर',
      'currency_detector': 'मुद्रा डिटेक्टर',
      'medication_assistant': 'दवा सहायक',
      'voice_memo': 'वॉइस मेमो',
      'spatial_nav': 'स्थानिक नेविगेशन',
      'islamic_features': 'इस्लामिक विशेषताएं',
      'entertainment': 'मनोरंजन और खेल',
      'status_center': 'स्थिति केंद्र',
      'settings': 'सेटिंग्स',
      'back': 'पीछे',
      'tap_to_enter': 'प्रवेश करने के लिए दो बार टैप करें।',
      'entering': 'प्रवेश कर रहे हैं',
      'help_hint': 'मदद। बाएं या दाएं स्वाइप करें।',
      'speed': 'भाषण की गति',
      'pitch': 'भाषण की पिच',
      'change_language': 'भाषा बदलें',
      'contrast_theme': 'उच्च कंट्रास्ट थीम',
      'fall_detection': 'गिरने का पता लगाने की स्थिति',
      'settings_welcome': 'सेटिंग्स। समायोजित करने के लिए ऊपर या नीचे स्वाइप करें।',
      'swipe_v_to_adjust': 'समायोजित करने के लिए ऊपर या नीचे स्वाइप करें।',
      'lang_name': 'हिन्दी',
      'lang_changed_to': 'भाषा को इसमें बदल दिया गया',
    },
    'es-ES': {
      'app_name': 'PELITA',
      'welcome': 'Bienvenido a Pelita.',
      'nav_hint': 'Desliza a la izquierda o derecha.',
      'text_scanner': 'Escáner de texto',
      'currency_detector': 'Detector de moneda',
      'medication_assistant': 'Asistente de medicación',
      'voice_memo': 'Nota de voz',
      'spatial_nav': 'Navegación espacial',
      'islamic_features': 'Funciones islámicas',
      'entertainment': 'Entretenimiento y juegos',
      'status_center': 'Centro de estado',
      'settings': 'Ajustes',
      'back': 'Atrás',
      'tap_to_enter': 'Toca dos veces para entrar.',
      'entering': 'Entrando en',
      'help_hint': 'Ayuda. Desliza horizontalmente.',
      'speed': 'Velocidad de voz',
      'pitch': 'Tono de voz',
      'change_language': 'Cambiar idioma',
      'contrast_theme': 'Tema de alto contraste',
      'fall_detection': 'Estado de detección de caídas',
      'settings_welcome': 'Ajustes. Desliza para ajustar.',
      'swipe_v_to_adjust': 'Desliza verticalmente para ajustar.',
      'lang_name': 'Español',
      'lang_changed_to': 'Idioma cambiado a',
    },
    'ru-RU': {
      'app_name': 'PELITA',
      'welcome': 'Добро пожаловать в Pelita.',
      'nav_hint': 'Проведите пальцем влево или вправо.',
      'text_scanner': 'Сканер текста',
      'currency_detector': 'Детектор валют',
      'medication_assistant': 'Помощник по лекарствам',
      'voice_memo': 'Голосовая заметка',
      'spatial_nav': 'Пространственная навигация',
      'islamic_features': 'Исламские функции',
      'entertainment': 'Развлечения и игры',
      'status_center': 'Центр состояния',
      'settings': 'Настройки',
      'back': 'Назад',
      'tap_to_enter': 'Коснитесь дважды, чтобы войти.',
      'entering': 'Вход в',
      'help_hint': 'Помощь. Проведите по горизонтали.',
      'speed': 'Скорость речи',
      'pitch': 'Высота голоса',
      'change_language': 'Изменить язык',
      'contrast_theme': 'Высококонтрастная тема',
      'fall_detection': 'Статус обнаружения падения',
      'settings_welcome': 'Настройки. Проведите для настройки.',
      'swipe_v_to_adjust': 'Проведите по вертикали для настройки.',
      'lang_name': 'Русский',
      'lang_changed_to': 'Язык изменен на',
    },
    'fr-FR': {
      'app_name': 'PELITA',
      'welcome': 'Bienvenue sur Pelita.',
      'nav_hint': 'Balayez vers la gauche ou la droite.',
      'text_scanner': 'Scanner de texte',
      'currency_detector': 'Détecteur de monnaie',
      'medication_assistant': 'Assistant de médication',
      'voice_memo': 'Mémo vocal',
      'spatial_nav': 'Navigation spatiale',
      'islamic_features': 'Fonctions islamiques',
      'entertainment': 'Divertissement et jeux',
      'status_center': 'Centre d\'état',
      'settings': 'Paramètres',
      'back': 'Retour',
      'tap_to_enter': 'Appuyez deux fois pour entrer.',
      'entering': 'Entrée dans',
      'help_hint': 'Aide. Balayez horizontalement.',
      'speed': 'Vitesse de lecture',
      'pitch': 'Hauteur de la voix',
      'change_language': 'Changer de langue',
      'contrast_theme': 'Thème à haut contraste',
      'fall_detection': 'Statut de détection de chute',
      'settings_welcome': 'Paramètres. Balayez pour ajuster.',
      'swipe_v_to_adjust': 'Balayez verticalement pour ajuster.',
      'lang_name': 'Français',
      'lang_changed_to': 'Langue changée en',
    },
    'tr-TR': {
      'app_name': 'PELITA',
      'welcome': 'Pelita\'ya hoş geldiniz.',
      'nav_hint': 'Sola veya sağa kaydırın.',
      'text_scanner': 'Metin Tarayıcı',
      'currency_detector': 'Para Birimi Dedektörü',
      'medication_assistant': 'İlaç Asistanı',
      'voice_memo': 'Sesli Not',
      'spatial_nav': 'Mekansal Navigasyon',
      'islamic_features': 'İslami Özellikler',
      'entertainment': 'Eğlence ve Oyunlar',
      'status_center': 'Durum Merkezi',
      'settings': 'Ayarlar',
      'back': 'Geri',
      'tap_to_enter': 'Girmek için iki kez dokunun.',
      'entering': 'Giriş yapılıyor',
      'help_hint': 'Yardım. Yatay kaydırın.',
      'speed': 'Konuşma hızı',
      'pitch': 'Ses tonu',
      'change_language': 'Dili değiştir',
      'contrast_theme': 'Yüksek kontrastlı tema',
      'fall_detection': 'Düşme algılama durumu',
      'settings_welcome': 'Ayarlar. Ayarlamak için kaydırın.',
      'swipe_v_to_adjust': 'Ayarlamak için dikey kaydırın.',
      'lang_name': 'Türkçe',
      'lang_changed_to': 'Dil şu şekilde değiştirildi',
    },
  };

  String translate(String key) {
    return _localizedValues[langCode]?[key] ?? _localizedValues['id-ID']![key]!;
  }
}
